version: "3.8"
services:
  bot:
    image: 'lordovat/testrep:mybot_latest' # Путь к образу из удаленного реестра
    restart: 'unless-stopped'
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - ADMIN=${ADMIN}
      
    depends_on:
      - redis
    links:
      - redis

  redis:
    image: 'redis:latest'
    restart: 'unless-stopped'
    ports:
      - "6379:6379"
  
  rabbitmq:
    image: 'rabbitmq:management'
    hostname: 'rabbitmq'
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=1111
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 1431655766