version: "3.8"
services:
  bot:
    image: 'lordovat/testrep:mybot_latest' # Путь к образу из удаленного реестра
    restart: 'unless-stopped'
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - ADMIN=${ADMIN}
      
    depends_on:
      - redis
    links:
      - redis

  redis:
    image: 'redis:latest'
    restart: 'unless-stopped'
    ports:
      - "6379:6379"
  nats:
    image: nats:latest
    entrypoint: /nats-server
    command: "-c /config/server.conf"
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - ./nats/data:/data
      - ./nats/config/server.conf:/config/server.conf
  
  nats-nui:
    image: ghcr.io/nats-nui/nui:latest
    container_name: nats-nui
    ports:
      - "31311:31311"  # Порт для доступа к NATS NUI
    volumes:
      - ./nui/db:/db
    depends_on:
      - nats