version: "3.8"
services:
  bot:
    image: 'lordovat/testrep:mybot_latest' # Путь к образу из удаленного реестра
    restart: 'unless-stopped'
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - ADMIN=${ADMIN}

    depends_on:
      - redis
    links:
      - redis

  redis:
    image: 'redis:latest'
    restart: 'unless-stopped'
    ports:
      - "6379:6379"
  nats:
    image: nats # Образ NATS
    entrypoint: /nats-server # Команда запуска сервера внутри контейнера
    ports:
      - "4222:4222" # Основной порт для взаимодействия с сервером
      - "8222:8222" # Порт для мониторинга сервера по HTTP (понадобится позже)
    volumes:
      - ./nats/data:/data