version: "3.9"

services:
  bot:
    build: .
    container_name: bot_gift
    command: [ "python", "main.py" ]
    env_file: .env
    depends_on:
      - db
      - redis
    restart: always

  # migrate:
  #   build: .
  #   container_name: migrate_gift
  #   command: [ "alembic", "upgrade", "head" ]
  #   env_file: .env
  #   volumes:
  #     - .:/app
  #   working_dir: /app
  #   depends_on:
  #     - db
  #   restart: "no" # однократный запуск

  db:
    image: postgres:latest
    container_name: postgres_gift
    environment:
      POSTGRES_DB: ${POSTGRES__DB}
      POSTGRES_USER: ${POSTGRES__USER}
      POSTGRES_PASSWORD: ${POSTGRES__PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:latest
    container_name: redis_gift
    ports:
      - "6379:6379"
    restart: always

volumes:
  pgdata:
