"""Change chat_id

Revision ID: f9a785501f45
Revises: df0e79190c70
Create Date: 2025-08-26 16:50:08.979693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9a785501f45'
down_revision: Union[str, None] = 'df0e79190c70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('giveaway_settings', 'text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('users', 'chat_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'chat_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('giveaway_settings', 'text',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
